### ISSUE TITLE
Passer en https ! 

### ISSUE THREAD

**Issue by pastjean** [coveo/source.coveo.com#45]
@GuiSim @wfortin @fdallairecoveo

https://search.coveo.com/#sort=relevancy&f:sourceFacet=[web%20-%20techblog]&f:languageFacet=[english]

les quicks view ne peuvent pas aller chercher le css (mixed content warning)... quick easy solution ? 
on laisse ca comme ca?

**Comment by vseguin** [comment]
On peut ajouter la feuille css par mapping file OU post-conversion script si necessaire.

**Comment by GuiSim** [comment]
HTTPS marche sans le domaine custom
(e.g. https://coveo.github.io/)

Sinon workaround :(

**Comment by GuiSim** [comment]
Cloudflare could help?
https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

**Comment by pastjean** [comment]
nop .. pour le faire avec cloudflare faut rediriger toute notre domaine *.coveo.com :sob:

**Comment by GuiSim** [comment]
Aww :cry:

**Comment by pastjean** [comment]
http://coveo.github.io/source.coveo.com/ ... just take a look :o
