### ISSUE TITLE
Add meta informations to posts

### ISSUE THREAD

**Issue by wfortin** [coveo/source.coveo.com#50]
Add meta for twitter, g+, opengraph and more.
http://moz.com/blog/meta-data-templates-123

**Comment by pastjean** [comment]
http://opengraphprotocol.org/

**Comment by pastjean** [comment]
oh ya tout dans ton autre lien!

**Comment by pastjean** [comment]
2ddc90f et le commit d'apres fix .. mais la moitiés des tags sont vides.. tu pourrais regarder ça

**Comment by wfortin** [comment]
We should document on how to add them in a post. Thanks @pastjean
